### ISSUE TITLE
Create a filter version of this plugin?

### ISSUE THREAD

**Issue by kiyoto** [tagomoris/fluent-plugin-parser#19]
This plugin is very useful in general, but even more so if it can be used as a filter. The reason is that it allows the user to apply multiple parsers one by one:

```aconf
<filter foo>
  type parser
  format /first regex/
  reserve_keys true
</filter>

<filter foo>
  type parser
  format /second regex/
  reserver_keys true
</filter>
...
```

We need to think about how to handle parse errors. (like the "suppress_parse_error" parameter in the current output plugin version). But in general, I'd love to see this as a filter as well.

**Comment by tagomoris** [comment]
Now we have `#emit_error_event` method to emit events w/ parse errors, for Fluentd v0.12.
I'll write filter plugin version if more requests exist :)

**Comment by kiyoto** [comment]
:+1: this would make grok_filter a piece of cake!

**Comment by bpesics** [comment]
+1

**Comment by tagomoris** [comment]
It's already implemented and released as `v0.6.0`, ...but i found that there's no documentation about it.
@cosmo0920 do you have time to add it?

**Comment by tagomoris** [comment]
It's already implemented and released as `v0.6.0`, ...but i found that there's no documentation about it.
@cosmo0920 do you have time to add it?

**Comment by cosmo0920** [comment]
OK, I'll add it.

**Comment by tagomoris** [comment]
#25 merged. Done!
