### ISSUE TITLE
undefined local variable

### ISSUE THREAD

**Issue by tagomoris** [tagomoris/fluent-plugin-parser#21]
https://github.com/tagomoris/fluent-plugin-parser/blob/master/lib/fluent/plugin/out_parser.rb#L117

**Comment by antofran22** [comment]
Do you know if you will find time this week to patch it?

**Comment by tagomoris** [comment]
Fixed and released v0.4.1.
I'm sorry for late fix, because I'm in vacation now :)

**Comment by antofran22** [comment]
thanks for fixing it and enjoy your vacation :-)
